### ISSUE TITLE
CONCEPT: registrator.module - initialization

### ISSUE THREAD

**Issue by JozefFlakus** [baristaJS/barista-core#30]
During unit testing of our `registrator.module` I've came into conclusion that module initialization should be refactored a little bit.

**Current problem:**
Our current implementation is based on module global `config` object. It makes unit testing a little bit hard and makes module behaviour unpredictable which will be more prone to bugs.

**Proposed refactor:**
We should avoid global state and scope execution config and use different module initialization interface:

Old interface:
```javascript
barista.setConfig({ app, databaseUri: MONGODB_URI });
barista.registerModel({ name: 'User', schema: UserSchema });
```

New proposed interface:
```javascript
const modelRegistrator = barista.modelRegistrator({ app, databaseUri: MONGODB_URI });
modelRegistrator.registerModel({ name: 'User', schema: UserSchema });
```

This way our registrator module will have his config hoisted inside returned object.
It will be similar to express app initialization:

```javascript
const app = express();
app.use(...);
```

Maybe this is a good time to talk also about interface naming.

**Comment by sebastianmusial** [comment]
@JozefFlakus For me It's ok.
